version: "3.8"
services:
    app:
        container_name: svelte-todo-dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        ports:
            - "3000:3000"
        stdin_open: true
    prod:
        container_name: svelte-todo-prod
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "80:80"
        stdin_open: true
