version: "3.8"
services:
    app:
        container_name: svelte-todo-prod
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "80:80"
        stdin_open: true
