version: "3.8"
services:
    app:
        container_name: svelte-todo-dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        ports:
            - "3000:3000"
        stdin_open: true
